project:
  type: website

website:
  title: "MapAgora Dashboard"
  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: Learn
        href: learn.qmd
      - text: Where to Start
        href: where_to_start.qmd
      - text: Map
        href: map.qmd
      - text: Table
        href: table.qmd
      - text: Compare
        href: compare.qmd
      - text: About
        href: about.qmd

format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: style.css
