project:
  type: website

website:
  title: "Agora Dashboard"
  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: Civic Map
        href: map.qmd  
      - text: Civic Table
        href: table.qmd
      - text: About
        href: about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
